### ISSUE TITLE
Generating PFM and mask files for new sizes?

### ISSUE THREAD

**Issue by DanAndersen** [tdsuper/SPHORB#2]
Hi,
First of all, thank you very much for creating this library. It will be very useful in my research!

Second, I was interested in using this on larger input image sizes (3840x1920). It appears that because of the reliance on the PFM and mask files in the Data directory, the maximum supported size is 1280x640. Do you have any code for generating these file for arbitrary input image sizes?

**Comment by tdsuper** [comment]
Hi, thanks for the interests in our work. 

We are quite sorry that currently we do not have code to generate the PFM and mask files for arbitrary input image sizes. However you can write the code by yourself. This is because these files are only used to store the information of the storage grid (Fig. 3c in our paper). If you understand the structure of storage grid, it is not difficult to write the code.

Another strategy is resizing the high resolution images to 1280x640 and using our code. However this way may sacrifice the performance.

**Comment by xiaohulugo** [comment]
Hi, the code gets 522 and 512 key points on image 2_1 and 2_2, respectively, but only 8 matches. While on the first image pair, there are 242 matches. Do you have the same result on your computer?
